### PR TITLE
Fix crash when invalid number input when editing 

### LINKED ISSUE #177: [PE-D][Tester A] Exception throw when editing prices
`NumberFormatException` thrown for the following commands.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: lesterong/ped#9

### PR DESCRIPTION
**Pull request by yuehernkang**
closes #177

### CODE REVIEW

File: src/main/java/seedu/condonery/ui/MainWindow.java [hunk 1]
```diff
@@ -177,6 +177,7 @@ public void handleImageUpload(String name) {
         );
 
         File file = fileChooser.showOpenDialog(primaryStage);
+        System.out.println(logic.getUserImageDirectoryPath());
```
Comment (misterpuffin) [inline src/main/java/seedu/condonery/ui/MainWindow.java:180]: can remove this print statement!

File: src/main/java/seedu/condonery/ui/MainWindow.java [hunk 2]
```diff
@@ -185,6 +186,7 @@ public void handleImageUpload(String name) {
                     StandardCopyOption.REPLACE_EXISTING
                 );
             } catch (IOException ex) {
+                ex.printStackTrace();
```
Comment (misterpuffin) [inline src/main/java/seedu/condonery/ui/MainWindow.java:189]: this too!

File: src/main/java/seedu/condonery/logic/commands/property/EditPropertyCommand.java [hunk 3]
```diff
@@ -110,11 +112,14 @@ public CommandResult execute(Model model) throws CommandException {
             throw new CommandException(MESSAGE_DUPLICATE_PROPERTY);
         }
 
-        File existingImage = new File(propertyToEdit.getImagePath().toString());
-        if (existingImage.exists()) {
-            existingImage.renameTo(new File(editedProperty.getImagePath().toString()));
+        if (propertyToEdit.getImagePath() != null) {
```
Comment (misterpuffin) [inline src/main/java/seedu/condonery/logic/commands/property/EditPropertyCommand.java:115]: not sure if i agree with this checking, since getImagePath should never be null. Doing this might prevent errors but is more likely burying the issue. 

The main problem is we need to be careful whenever creating Properties that they are created with the correct imageDirectoryPath

Comment (yuehernkang) [reply src/main/java/seedu/condonery/logic/commands/property/EditPropertyCommand.java]: Fixed in the latest commit !

File: src/main/java/seedu/condonery/ui/MainWindow.java (hunk 2 above)
Comment (yuehernkang) [reply src/main/java/seedu/condonery/ui/MainWindow.java]: Fixed in the latest commit !

File: src/main/java/seedu/condonery/ui/MainWindow.java (hunk 1 above)
Comment (yuehernkang) [reply src/main/java/seedu/condonery/ui/MainWindow.java]: Fixed in the latest commit !

**Review by zacchaeuschok — APPROVED** [review]

**Comment by lkwlkww** [comment]
The max value of an Integer in java is `2,147,483,647` and while rare, there are houses with prices that can exceed the max integer value. Since Condonery only accepts prices up to that amount, I think its a feature flaw that can be fixed by using `Longs` rather than `Integers`. However, since fixing feature flaws are prohibited in the feature freeze (see [here](https://nus-cs2103-ay2223s1.github.io/website/schedule/week12/project.html)), I guess we could just keep this in mind.

**Review by lkwlkww — APPROVED** [review]
